/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ServicesPackage;
import generated.grpc.lightingcontrol.LightingControlGrpc.LightingControlStub;
import generated.grpc.lightingcontrol.LightingControlGrpc;
import generated.grpc.lightingcontrol.turnOnLightRequest;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import java.awt.Color;
import javax.swing.JRadioButton;
/**
 *
 * @author Prasanna
 */
public class GUILightingControl extends javax.swing.JFrame {
    private LightingControlGrpc.LightingControlBlockingStub syncStub;
    ManagedChannel channel = ManagedChannelBuilder
                .forAddress("localhost", 50051)
                .usePlaintext()
                .build();
    //syncStub = LightingControlGrpc.newBlockingStub(channel);

    /**
     * Creates new form GUILightingControl
     */
    public GUILightingControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        numLight1 = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        trueNumlight1btn = new javax.swing.JRadioButton();
        falseNumlight1btn = new javax.swing.JRadioButton();
        numLight1onoroff = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        responseServertextarea = new javax.swing.JTextArea();
        num1Light = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        numLight1.setText("Light1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headingLabel.setText("                   Lighting Control");

        trueNumlight1btn.setText("ON");
        trueNumlight1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueNumlight1btnActionPerformed(evt);
            }
        });

        falseNumlight1btn.setText("OFF");
        falseNumlight1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseNumlight1btnActionPerformed(evt);
            }
        });

        numLight1onoroff.setText("Response");

        responseServertextarea.setColumns(20);
        responseServertextarea.setRows(5);
        jScrollPane1.setViewportView(responseServertextarea);

        num1Light.setText("Light 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numLight1onoroff, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1Light, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(trueNumlight1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(falseNumlight1btn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trueNumlight1btn)
                    .addComponent(falseNumlight1btn)
                    .addComponent(num1Light))
                .addGap(103, 103, 103)
                .addComponent(numLight1onoroff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void trueNumlight1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueNumlight1btnActionPerformed
        turnOnLightRequest request = turnOnLightRequest.newBuilder()
                .setNumLight1(true)
                .build();
        boolean ON = true;
        if(ON){
            responseServertextarea.setText("Light number 1 is turned on");
            responseServertextarea.setBackground(Color.GREEN);
        }      
    }//GEN-LAST:event_trueNumlight1btnActionPerformed

    private void falseNumlight1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseNumlight1btnActionPerformed
        boolean OFF = true;
        if(OFF){
            responseServertextarea.setText("Light number 1 is not on");
            responseServertextarea.setBackground(Color.RED);
        } 
    }//GEN-LAST:event_falseNumlight1btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILightingControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILightingControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton falseNumlight1btn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel num1Light;
    private javax.swing.JButton numLight1;
    private javax.swing.JLabel numLight1onoroff;
    private javax.swing.JTextArea responseServertextarea;
    private javax.swing.JRadioButton trueNumlight1btn;
    // End of variables declaration//GEN-END:variables
}
