/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ServicesPackage;

import java.awt.Color;

/**
 *
 * @author Prasanna
 */
public class GUIMotionAlertNdAction extends javax.swing.JFrame {

    /**
     * Creates new form GUIMotionAlertNdAction
     */
    public GUIMotionAlertNdAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        motionalertOn = new javax.swing.JSeparator();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        headingLabel = new javax.swing.JLabel();
        motionnotificationLabel = new javax.swing.JLabel();
        notificationonORoff = new javax.swing.JToggleButton();
        actionLabel = new javax.swing.JLabel();
        actionRequiredyesbtn = new javax.swing.JButton();
        actionRequirednobtn = new javax.swing.JButton();
        motionalertEnabled = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sendNotification = new javax.swing.JButton();
        actionTakenlabel = new javax.swing.JLabel();
        actionNeededon = new javax.swing.JCheckBox();
        noAction = new javax.swing.JCheckBox();
        textareaLabel = new javax.swing.JLabel();
        motionalertLabel = new javax.swing.JLabel();
        motiondetectLabel = new javax.swing.JLabel();
        detectedBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextarea = new javax.swing.JTextArea();

        jToggleButton1.setText("jToggleButton1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headingLabel.setText("Motion Alert and Action Service");

        motionnotificationLabel.setText("Motiion notification");

        notificationonORoff.setText("ON/OFF");
        notificationonORoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationonORoffActionPerformed(evt);
            }
        });

        actionLabel.setText("Action");

        actionRequiredyesbtn.setText("Yes");
        actionRequiredyesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRequiredyesbtnActionPerformed(evt);
            }
        });

        actionRequirednobtn.setText("No");
        actionRequirednobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionRequirednobtnActionPerformed(evt);
            }
        });

        motionalertEnabled.setText("Enabled");
        motionalertEnabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motionalertEnabledActionPerformed(evt);
            }
        });

        jLabel2.setText("Alert notification");

        sendNotification.setText("Send");
        sendNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNotificationActionPerformed(evt);
            }
        });

        actionTakenlabel.setText("Action Needed");

        actionNeededon.setText("ON");
        actionNeededon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNeededonActionPerformed(evt);
            }
        });

        noAction.setText("NA");
        noAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionActionPerformed(evt);
            }
        });

        textareaLabel.setText("Message");

        motionalertLabel.setText("Motion Alert");

        motiondetectLabel.setText("Motion");

        detectedBtn.setText("Detected");
        detectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detectedBtnActionPerformed(evt);
            }
        });

        messageTextarea.setColumns(20);
        messageTextarea.setRows(5);
        jScrollPane2.setViewportView(messageTextarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textareaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motionnotificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motionalertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actionTakenlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motiondetectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detectedBtn)
                            .addComponent(sendNotification)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actionNeededon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(noAction, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actionRequiredyesbtn)
                                .addGap(36, 36, 36)
                                .addComponent(actionRequirednobtn))
                            .addComponent(notificationonORoff, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motionalertEnabled)))
                    .addComponent(jScrollPane2))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motionnotificationLabel)
                    .addComponent(notificationonORoff))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionLabel)
                    .addComponent(actionRequiredyesbtn)
                    .addComponent(actionRequirednobtn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motionalertEnabled)
                    .addComponent(motionalertLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                        .addComponent(motiondetectLabel)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detectedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendNotification, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionTakenlabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(actionNeededon)
                        .addComponent(noAction)))
                .addGap(24, 24, 24)
                .addComponent(textareaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificationonORoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationonORoffActionPerformed
        if(notificationonORoff.isSelected()){
            notificationonORoff.setText("ON"); 
            motionalertEnabled.setEnabled(true);
            motionalertEnabled.setBackground(Color.GREEN);
        } else {
            notificationonORoff.setText("OFF"); 
            notificationonORoff.setBackground(Color.RED);
        }
    }//GEN-LAST:event_notificationonORoffActionPerformed

    private void motionalertEnabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motionalertEnabledActionPerformed
      
            detectedBtn.setEnabled(true);
        
    }//GEN-LAST:event_motionalertEnabledActionPerformed

    private void actionRequiredyesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRequiredyesbtnActionPerformed
        if(actionRequiredyesbtn.isSelected()){
            actionRequiredyesbtn.setBackground(Color.GREEN);
            actionNeededon.isSelected();
        }
    }//GEN-LAST:event_actionRequiredyesbtnActionPerformed

    private void actionNeededonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNeededonActionPerformed
        actionRequiredyesbtn.getSelectedIcon();
        actionNeededon.isSelected();
    }//GEN-LAST:event_actionNeededonActionPerformed

    private void actionRequirednobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionRequirednobtnActionPerformed
        if(actionRequirednobtn.isSelected()){
            actionRequirednobtn.setBackground(Color.RED);
            noAction.setBackground(Color.RED);
        }
    }//GEN-LAST:event_actionRequirednobtnActionPerformed

    private void detectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detectedBtnActionPerformed
        detectedBtn.setEnabled(true);
        if(detectedBtn.isSelected()){
            sendNotification.isSelected();
            messageTextarea.setText("Warning! An alert detected in living area");
        }
    }//GEN-LAST:event_detectedBtnActionPerformed

    private void sendNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNotificationActionPerformed
         messageTextarea.setText("Warning! An alert detected in living area");

    }//GEN-LAST:event_sendNotificationActionPerformed

    private void noActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionActionPerformed
        
    }//GEN-LAST:event_noActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMotionAlertNdAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMotionAlertNdAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMotionAlertNdAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMotionAlertNdAction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMotionAlertNdAction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionLabel;
    private javax.swing.JCheckBox actionNeededon;
    private javax.swing.JButton actionRequirednobtn;
    private javax.swing.JButton actionRequiredyesbtn;
    private javax.swing.JLabel actionTakenlabel;
    private javax.swing.JButton detectedBtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextArea messageTextarea;
    private javax.swing.JButton motionalertEnabled;
    private javax.swing.JLabel motionalertLabel;
    private javax.swing.JSeparator motionalertOn;
    private javax.swing.JLabel motiondetectLabel;
    private javax.swing.JLabel motionnotificationLabel;
    private javax.swing.JCheckBox noAction;
    private javax.swing.JToggleButton notificationonORoff;
    private javax.swing.JButton sendNotification;
    private javax.swing.JLabel textareaLabel;
    // End of variables declaration//GEN-END:variables
}
